# run-npm-dev-combined-dockerfile

FROM node:latest

WORKDIR /app

COPY npmrundev-env .
COPY launch_project.sh .

RUN git clone https://github.com/TimeEnjoyed/npm-run-dev-api.git
RUN git clone https://github.com/TimeEnjoyed/npm-run-dev-front-end.git
RUN mv npmrundev-env npm-run-dev-api/.env
RUN cd npm-run-dev-api && npm install . && cd ..
RUN cd npm-run-dev-front-end && npm install . && cd ..
RUN chmod +x /app/launch_project.sh

EXPOSE 5173
EXPOSE 3000

CMD ["/bin/bash", "-c", "/app/launch_project.sh"]

